### ISSUE TITLE
Dropdown should show titles instead of the handles

### ISSUE THREAD

**Issue by ReneWeCode** [riasvdv/statamic-linkit#25]
The dropdown with the collection entry options shows the handles. Should definitely be the titles.

![selectoption_titles](https://user-images.githubusercontent.com/43215436/90648797-457caa80-e23a-11ea-850c-e27f59e4a34c.png)

**Comment by riasvdv** [comment]
It definitely should, however it's currently impossible to do because the front-end component only gets the handles back from the configuration.

They are being parsed through a translation string, so if you add a file in for example: `resources/lang/en.json` for the `en` locale, you can translate them:

```json
{
    "pages": "Sider",
    "langingpages": "Landingsider"
}
```

**Comment by ReneWeCode** [comment]
Thank you @riasvdv. Will try that out 👍
